version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    expose:
      - "8081"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - backend
    ports:
      - "80:80"  # Nginx가 8080 포트로 내부 백엔드에 접근
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
